version: '3'

services:
  wine-taster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wine-taster-network
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wine-taster-network
    command: --default-authentication-plugin=mysql_native_password
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - wine-taster-network
networks:
  wine-taster-network:
volumes:
  db_data: