name: Tests
on: [push]
env:
    API_KEY: "an-api-key"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update lock file
      run: npm install
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm run test:dev
